name: Build and Release EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write     

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          cmd /c dir D:\a\ChromecastRescue\ChromecastRescue /s
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --windowed --noupx ChromecastRescue.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChromecastRescue
          path: dist/ChromecastRescue.exe

  release:
    needs: build
    runs-on: windows-latest  # Changed from ubuntu-latest to windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ChromecastRescue
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: dist/ChromecastRescue.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
